# Generated by Django 5.2.6 on 2025-09-28 15:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnpj', models.CharField(help_text='CNPJ da empresa (apenas números)', max_length=14, unique=True)),
                ('razao_social', models.CharField(max_length=255)),
                ('nome_fantasia', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
            },
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=60)),
                ('descricao', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
            },
        ),
        migrations.CreateModel(
            name='NotaFiscal',
            fields=[
                ('chave_acesso', models.CharField(help_text='Chave de Acesso da NFe com 44 dígitos', max_length=44, primary_key=True, serialize=False, unique=True)),
                ('numero', models.IntegerField()),
                ('serie', models.IntegerField()),
                ('data_emissao', models.DateTimeField()),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=15)),
                ('destinatario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notas_recebidas', to='analisador.empresa')),
                ('emitente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notas_emitidas', to='analisador.empresa')),
            ],
            options={
                'verbose_name': 'Nota Fiscal',
                'verbose_name_plural': 'Notas Fiscais',
            },
        ),
        migrations.CreateModel(
            name='ItemNotaFiscal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.DecimalField(decimal_places=4, max_digits=15)),
                ('valor_unitario', models.DecimalField(decimal_places=4, max_digits=15)),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=15)),
                ('nota_fiscal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='analisador.notafiscal')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='analisador.produto')),
            ],
            options={
                'verbose_name': 'Item da Nota Fiscal',
                'verbose_name_plural': 'Itens da Nota Fiscal',
                'unique_together': {('nota_fiscal', 'produto')},
            },
        ),
    ]
